// Main UI controller that manages job lifecycle and renders components based on processing state
import React, { useState } from "react";
import UploadAudio from "./components/UploadAudio";
import JobStatus from "./components/JobStatus";
import "./App.css";

// Orchestrates frontend state: upload → processing → polling → result display
function App() {
  // Stores backend job ID for tracking async processing
  const [jobId, setJobId] = useState(null);

  // Tracks UI state across job lifecycle
  const [status, setStatus] = useState("idle"); // idle | processing | completed

  // Holds final processed result returned from backend
  const [result, setResult] = useState(null);

  return (
    <div className="container">
      <h1>AI Care Notes</h1>

      {/* Upload component triggers backend processing pipeline */}
      <UploadAudio
        setJobId={setJobId}
        setStatus={setStatus}
      />

      {/* Displays loading indicator while backend processes the job */}
      {status === "processing" && <p className="loading">Processing your audio...</p>}

      {/* Polls backend until job is completed */}
      {jobId && (
        <JobStatus
          jobId={jobId}
          setStatus={setStatus}
          setResult={setResult}
        />
      )}

      {/* Renders final AI-generated output once processing is complete */}
      {status === "completed" && result && (
        <div className="result-box">

          {/* Clinical summary generated by AI */}
          <div className="card">
            <h2>Summary</h2>
            <p>{result.summary?.summary}</p>
          </div>

          {/* Risk analysis with severity-based highlighting */}
          <div className="card">
            <h3>Risks</h3>
            <ul>
              {/* Render each detected risk with severity styling */}
              {result.summary?.risks?.map((r, i) => (
                <li key={i} className={`risk-${r.severity?.toLowerCase()}`}>
                  ⚠️ <strong>{r.type}</strong> — {r.severity}
                </li>
              ))}
            </ul>
          </div>

          {/* Recommended caregiver actions */}
          <div className="card">
            <h3>Actions</h3>
            <ul>
              {result.summary?.actions?.map((a, i) => <li key={i}>{a}</li>)}
            </ul>
          </div>
        </div>
      )}
    </div>
  );
}

export default App;